# Generated by Django 4.1 on 2022-09-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="user",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("receipt_number", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=300)),
                ("address", models.TextField()),
                ("pincode", models.IntegerField()),
                ("phone", models.BigIntegerField()),
                ("is_hindu", models.BooleanField(default=True)),
                (
                    "maasa",
                    models.CharField(
                        choices=[("chaitra", "chaitra"), ("vaishaka", "vaishaka")],
                        max_length=100,
                    ),
                ),
                ("paksha", models.CharField(max_length=100)),
                (
                    "thithi",
                    models.CharField(
                        choices=[("prathama", "prathama"), ("dwithiya", "dwithiya")],
                        max_length=100,
                    ),
                ),
                ("date", models.DateField(default="")),
            ],
        ),
    ]
