# Generated by Django 4.1 on 2022-09-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data1", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="month",
            field=models.CharField(
                blank=True,
                choices=[
                    (1, "January"),
                    (2, "February"),
                    (3, "March"),
                    (4, "April"),
                    (5, "May"),
                    (6, "June"),
                    (7, "July"),
                    (8, "August"),
                    (9, "September"),
                    (10, "October"),
                    (11, "November"),
                    (12, "December"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="user", name="date", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="user",
            name="maasa",
            field=models.CharField(
                blank=True,
                choices=[("chaitra", "chaitra"), ("vaishaka", "vaishaka")],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="paksha",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="user",
            name="thithi",
            field=models.CharField(
                blank=True,
                choices=[("prathama", "prathama"), ("dwithiya", "dwithiya")],
                max_length=100,
            ),
        ),
    ]
