# Generated by Django 4.1 on 2022-09-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data1", "0002_user_month_alter_user_date_alter_user_maasa_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="date",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="month",
            field=models.CharField(
                blank=True, choices=[("january", "january")], max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="paksha",
            field=models.CharField(
                blank=True,
                choices=[("prathama", "prathama"), ("dwithiya", "dwithiya")],
                max_length=100,
            ),
        ),
    ]
