# Generated by Django 4.1 on 2022-09-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data1", "0003_alter_user_date_alter_user_month_alter_user_paksha"),
    ]

    operations = [
        migrations.CreateModel(
            name="maasa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(model_name="user", name="maasa",),
    ]
