# Generated by Django 4.1 on 2022-09-25 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("data1", "0004_maasa_remove_user_maasa"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="maasa",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="data1.maasa"
            ),
        ),
    ]
