# Generated by Django 4.1 on 2022-09-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data1", "0006_user_address_not_found_alter_user_maasa"),
    ]

    operations = [
        migrations.AddField(
            model_name="maasa",
            name="paksha",
            field=models.CharField(
                choices=[("krishna", "krishna"), ("shukla", "shukla")],
                default="",
                max_length=200,
            ),
        ),
    ]
