# Generated by Django 4.1 on 2022-09-25 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data1", "0007_maasa_paksha"),
    ]

    operations = [
        migrations.CreateModel(
            name="paksha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
    ]
