# Generated by Django 4.1 on 2022-09-25 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data1", "0008_paksha"),
    ]

    operations = [
        migrations.RemoveField(model_name="maasa", name="paksha",),
        migrations.AddField(
            model_name="maasa",
            name="paksha",
            field=models.ManyToManyField(to="data1.paksha"),
        ),
    ]
