# Generated by Django 4.1 on 2022-09-25 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("data1", "0009_remove_maasa_paksha_maasa_paksha"),
    ]

    operations = [
        migrations.RemoveField(model_name="maasa", name="paksha",),
        migrations.CreateModel(
            name="thithi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("thithi", models.CharField(max_length=100)),
                (
                    "maasa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="data1.maasa"
                    ),
                ),
                (
                    "paksha",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="data1.paksha"
                    ),
                ),
            ],
        ),
    ]
