# Generated by Django 4.1 on 2022-09-25 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("data1", "0010_remove_maasa_paksha_thithi"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thithi",
            name="thithi",
            field=models.CharField(
                choices=[("prathama", "prathama"), ("dwithiya", "dwithiya")],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="thithi",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="data1.thithi",
            ),
        ),
    ]
