# Generated by Django 4.1 on 2022-09-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data1", "0011_alter_thithi_thithi_alter_user_thithi"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="month",
            field=models.CharField(
                blank=True, choices=[("january", "january")], max_length=100, null=True
            ),
        ),
    ]
