# Generated by Django 4.1 on 2022-09-25 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("data1", "0012_alter_user_month"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="thithi",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="data1.thithi",
            ),
        ),
    ]
