# Generated by Django 4.1 on 2022-09-25 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data1", "0013_alter_user_thithi"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="thithi",),
    ]
