# Generated by Django 4.1 on 2022-09-25 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("data1", "0014_remove_user_thithi"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="thithi1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="data1.thithi",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="thithi2",
            field=models.CharField(
                blank=True,
                choices=[("prathama", "prathama"), ("dwithiya", "dwithiya")],
                max_length=100,
            ),
        ),
    ]
