# Generated by Django 4.1 on 2022-09-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data1", "0015_user_thithi1_user_thithi2"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user", old_name="thithi1", new_name="thithi",
        ),
        migrations.RemoveField(model_name="user", name="maasa",),
        migrations.RemoveField(model_name="user", name="paksha",),
        migrations.RemoveField(model_name="user", name="thithi2",),
        migrations.AlterField(
            model_name="thithi",
            name="thithi",
            field=models.CharField(
                choices=[
                    ("ಪಾಡ್ಯ", "ಪಾಡ್ಯ"),
                    ("ದ್ವಿತೀಯ", "ದ್ವಿತೀಯ"),
                    ("ತೃತೀಯ", "ತೃತೀಯ"),
                    ("ಚತುರ್ಥಿ", "ಚತುರ್ಥಿ"),
                    ("ಪಂಚಮಿ", "ಪಂಚಮಿ"),
                ],
                max_length=100,
            ),
        ),
    ]
