# Generated by Django 4.1 on 2022-09-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data1", "0016_rename_thithi1_user_thithi_remove_user_maasa_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="thithi",
            name="pooja_day",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="month",
            field=models.CharField(
                blank=True, choices=[("January", "January")], max_length=100, null=True
            ),
        ),
    ]
