# Generated by Django 4.1 on 2022-09-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data1", "0017_thithi_pooja_day_alter_user_month"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thithi", name="pooja_day", field=models.DateField(null=True),
        ),
    ]
