# Generated by Django 4.1 on 2022-09-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data1", "0018_alter_thithi_pooja_day"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thithi",
            name="thithi",
            field=models.CharField(
                choices=[
                    ("ಪಾಡ್ಯ", "ಪಾಡ್ಯ"),
                    ("ದ್ವಿತೀಯ", "ದ್ವಿತೀಯ"),
                    ("ತೃತೀಯ", "ತೃತೀಯ"),
                    ("ಚತುರ್ಥಿ", "ಚತುರ್ಥಿ"),
                    ("ಪಂಚಮಿ", "ಪಂಚಮಿ"),
                    ("ಅಮಾವಾಸ್ಯೆ", "ಅಮಾವಾಸ್ಯೆ"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="month",
            field=models.CharField(
                blank=True,
                choices=[
                    ("January", "January"),
                    ("February", "February"),
                    ("March", "March"),
                    ("April", "April"),
                    ("May", "May"),
                    ("June", "June"),
                    ("July", "July"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
