# Generated by Django 4.1 on 2022-09-27 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data1", "0019_alter_thithi_thithi_alter_user_date_alter_user_month"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="month",),
    ]
