# Generated by Django 4.1 on 2022-09-27 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data1", "0020_remove_user_month"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="date",
            field=models.DateField(blank=True, default="2000-01-01", null=True),
        ),
    ]
