# Generated by Django 4.1 on 2022-09-27 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data1", "0021_alter_user_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="amount",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="i_amount",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
