# Generated by Django 4.1 on 2022-09-27 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data1", "0022_user_amount_user_i_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thithi", name="thithi", field=models.IntegerField(),
        ),
    ]
