# Generated by Django 4.1 on 2022-09-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data1", "0023_alter_thithi_thithi"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user", name="is_hindu", field=models.BooleanField(),
        ),
    ]
