# Generated by Django 4.1 on 2022-09-28 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data1", "0024_alter_user_is_hindu"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=11
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="i_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=11
            ),
        ),
        migrations.AlterField(
            model_name="user", name="is_hindu", field=models.BooleanField(default=True),
        ),
    ]
