# Generated by Django 4.1 on 2022-10-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data1", "0025_alter_user_amount_alter_user_i_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user", name="year", field=models.IntegerField(default=2000),
        ),
    ]
