# Generated by Django 4.1 on 2022-10-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data1", "0026_user_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user", name="year", field=models.IntegerField(),
        ),
    ]
