# Generated by Django 4.1 on 2022-10-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data1", "0027_alter_user_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name="user",
            name="i_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
    ]
